INSERT INTO courses(code, dept_prefix, course_name) VALUES('1030', 'ADMN', 'Arch Exploration & Planning') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('1824', 'ADMN', 'Student Success Labs') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('6600', 'ADMN', 'Summer Administ Registration') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('6700', 'ADMN', 'Academic Orientation Seminar For Graduate Students') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('6800', 'ADMN', 'Ta Training Seminar') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('6960', 'ADMN', 'Graduate Away Opportunity') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('6980', 'ARCH', 'Master''s Project') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('2210', 'ARTS', 'Sculpture I') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('2230', 'ARTS', '3d Digital Modeling') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('2560', 'ARTS', 'Game Sound & Musical Play') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('2700', 'ARTS', 'Sound Recording & Prod I') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('2750', 'ARTS', 'Private Music Lessons: Flute') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('2960', 'ARTS', 'Concept Art') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('4090', 'ARTS', 'Art & Code Interactivity') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('4280', 'ARTS', '3d Technical Direction') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('4440', 'ARTS', 'Music, Sound & Screen Media') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('1520', 'ASTR', 'Stars, Galaxies And The Cosmos') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('2120', 'ASTR', 'Earth And Sky') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('2150', 'ASTR', 'Cosmology: Our Universe') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('4760', 'BCBP', 'Molecular Biochemistry I') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('6990', 'BCBP', 'Master''s Thesis') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('9990', 'BCBP', 'Dissertation') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('1010', 'BIOL', 'Introduction To Biology') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('1015', 'BIOL', 'Introduction To Biology Laboratory') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('1960', 'BIOL', 'Biology In Popular Fiction') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('2960', 'BIOL', 'Field Experiences Aquatic Biol') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('2961', 'BIOL', 'Field Experiences Aquatic Biol') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('2962', 'BIOL', 'Sense And Signal') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('2963', 'BIOL', 'Birds And Dinosaurs') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('2964', 'BIOL', 'Apes And Monkeys') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('4200', 'BIOL', 'Biostatistics') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('4320', 'BIOL', 'Microbiology Laboratory') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('4720', 'BIOL', 'Molecular Biology Lab') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('4740', 'BIOL', 'Advanced Cell Biology Laboratory') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('4760', 'BIOL', 'Molecular Biochemistry I') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('4962', 'BIOL', 'Comptl Biol: Algorithm & App') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('6970', 'BIOL', 'Masters Professional Project') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('6990', 'BIOL', 'Master''s Thesis') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('9990', 'BIOL', 'Dissertation') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('2050', 'BMED', 'Programming For Biomed Engr') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('2100', 'BMED', 'Biomaterials Sci & Engineering') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('2300', 'BMED', 'Bioimaging/ Bioinstrumentation') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('2540', 'BMED', 'Biomechanics') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('4010', 'BMED', 'Biomedical Engineering Lab') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('4200', 'BMED', 'Modeling Of Biomedical Systems') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('4250', 'BMED', 'Biomed Transport Phenomena') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('6103', 'BUSN', 'Markets, Strategy & People') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('6105', 'BUSN', 'Agile Planning & Execution') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('6107', 'BUSN', 'Changing And Innovating') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('6300', 'BUSN', 'Leaders & Strategy') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('6305', 'BUSN', 'Leaders In Dynamic Markets') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('6310', 'BUSN', 'Leaders Making Financial Decsn') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('6315', 'BUSN', 'Leaders Planning And Executing') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('6320', 'BUSN', 'Leaders Leading People') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('6325', 'BUSN', 'Leaders Charting The Course') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('6500', 'BUSN', 'Programs And Strategy') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('6501', 'BUSN', 'Program Performance Plng') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('6502', 'BUSN', 'Program Execution Mgmt') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('2050', 'CHME', 'Introduction To Computational Chemical Engineering') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('2100', 'CHME', 'Chemical Process Safety') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('4020', 'CHME', 'Transport Phenomena II') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('4610', 'CHME', 'Polymer Procss & Plstc Tech') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('4962', 'CHME', 'Chem Eng In Therapeutics Biopr') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('4964', 'CHME', 'Prof Pathways In Chem Eng') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('4965', 'CHME', 'Chem And Bioprocess Sims') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('6990', 'CHME', 'Masters Thesis') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('9990', 'CHME', 'Dissertation') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('2230', 'CHEM', 'Organic Chemistry Lab I') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('2240', 'CHEM', 'Organic Chemistry Lab II') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('2250', 'CHEM', 'Organic Chemistry I') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('2260', 'CHEM', 'Organic Chemistry II') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('4010', 'CHEM', 'Inorganic Chemistry II') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('4410', 'CHEM', 'Macroscopic Physical Chemistry') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('4440', 'CHEM', 'Physical Chem For Life Science') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('4530', 'CHEM', 'Modern Techniques In Chemistry') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('4760', 'CHEM', 'Molecular Biochemistry I') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('4820', 'CHEM', 'Food Chemistry & Technology') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('4961', 'CHEM', 'Intro To Nanomaterials Chem') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('6990', 'CIVL', 'Masters Thesis') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('9990', 'CIVL', 'Dissertation') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('2120', 'COGS', 'Intro To Cognitive Science') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('2340', 'COGS', 'Introduction To Linguistics') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('4360', 'COGS', 'Behavioral Neuroscience') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('4420', 'COGS', 'Game Ai') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('4700', 'COGS', 'Hormones, Brain & Behavior') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('4960', 'COGS', 'Extended Cognition') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('4961', 'COGS', 'Intro Deep Learn Nat Lang Gen') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('6960', 'COGS', 'Intro Deep Learn Nat Lang Gen') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('2440', 'COMM', 'Documentary Film') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('2520', 'COMM', 'Comm Theory & Practice') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('2660', 'COMM', 'Introduction To Graphic Design') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('2961', 'COMM', 'Social Media And Society') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('2962', 'COMM', 'Language And Society') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('4288', 'COMM', 'Health Comm In Practice') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('4535', 'COMM', 'Social Media: East & West') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('4880', 'COMM', 'Interactive Data Visualization') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('6880', 'COMM', 'Interactive Data Visualization') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('1100', 'CSCI', 'Computer Science I') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('2300', 'CSCI', 'Introduction To Algorithms') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('2600', 'CSCI', 'Principles Of Software') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('2960', 'CSCI', 'Rcos') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('4150', 'CSCI', 'Introduction To Artificial Intelligence') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('4170', 'CSCI', 'Projects In Ai & Machine Lrng') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('4210', 'CSCI', 'Operating Systems') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('4260', 'CSCI', 'Graph Theory') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('4440', 'CSCI', 'Software Design & Docume') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('4800', 'CSCI', 'Numerical Computing') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('4960', 'CSCI', 'Introduction To Research') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('4961', 'CSCI', 'Game Ai') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('4962', 'CSCI', 'Intro Deep Learn Nat Lang Gen') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('6980', 'CSCI', 'Master''s Project') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('6990', 'CSCI', 'Masters Thesis') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('9990', 'CSCI', 'Dissertation') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('1100', 'ENGR', 'Intro To Engr Analysis') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('1200', 'ENGR', 'Eng Graphics & Cad') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('1300', 'ENGR', 'Engineeriing Processes') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('1600', 'ENGR', 'Materials Science') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('2050', 'ENGR', 'Intro Engineering Design') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('2090', 'ENGR', 'Engineering Dynamics') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('2300', 'ENGR', 'Electronic Instrumentation') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('2530', 'ENGR', 'Strength Of Materials') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('2600', 'ENGR', 'Mod & Analysis Uncertainty') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('4010', 'ENGR', 'Pd: Leadership Competencies') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('4760', 'ENGR', 'Engineering Economics') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('4962', 'ENGR', 'Ds For Wearable Sensor Data') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('6200', 'ENGR', 'Data-driven Decision Making') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('6215', 'ENGR', 'Modeling, Forecasting, Simultn') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('6216', 'ENGR', 'Applied Analytics') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('6220', 'ENGR', 'Data Architecture') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('6221', 'ENGR', 'Machine Learning Frameworks') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('6222', 'ENGR', 'Deep Learning In Ai Systems') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('6231', 'ENGR', 'Lean Six Sigma II') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('6970', 'ENGR', 'Masters Professional Project') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('4190', 'ERTH', 'Environmental Measurements') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('2010', 'ECON', 'Intermediate Microeconomic Theory') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('2020', 'ECON', 'Intermediate Macroeconomic Theory') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('4130', 'ECON', 'Money & Banking') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('4190', 'ECON', 'International Economics And Globalization') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('4230', 'ECON', 'Environmental Economics') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('4570', 'ECON', 'Econometrics') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('2010', 'ECSE', 'Electric Circuits') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('2110', 'ECSE', 'Electrical Energy Systems') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('2410', 'ECSE', 'Signals And Systems') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('2500', 'ECSE', 'Engineering Probability') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('2660', 'ECSE', 'Comp Architecture & Networks') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('2960', 'ECSE', 'Practicum-college Teaching I') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('6970', 'ECSE', 'Professional Project') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('6980', 'ECSE', 'Master''s Project') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('6990', 'ECSE', 'Masters Thesis') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('9990', 'ECSE', 'Dissertation') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('4370', 'ENVE', 'Applied Hydrology & Design') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('9990', 'ENVE', 'Dissertation') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('2520', 'GSAS', 'Intro To Game Storytelling') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('2560', 'GSAS', 'Game Sound & Musical Play') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('2960', 'GSAS', 'Analog Role-playing Games') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('2961', 'GSAS', 'Introduction To World Building') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('2962', 'GSAS', 'Concept Art') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('4440', 'GSAS', 'Music, Sound & Screen Media') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('4510', 'GSAS', 'Experimental Game Design') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('4960', 'GSAS', 'Intro Deep Learn Nat Lang Gen') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('4400', 'ILEA', 'Independent Learning Exper') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('2530', 'ISYE', 'Information & Data Systems') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('4240', 'ISYE', 'Engr Proj Management') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('4600', 'ISYE', 'Determnstc Mthd In Op Rsrch') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('4962', 'ISYE', 'Ds For Wearable Sensor Data') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('6210', 'ISYE', 'Theory Of Prod Schedule') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('6610', 'ISYE', 'Systems Modeling In Dses') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('6980', 'ISYE', 'Masters Project') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('6990', 'ISYE', 'Master''s Thesis') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('9990', 'ISYE', 'Dissertation') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('1220', 'ITWS', 'It And Society') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('9990', 'ISCI', 'Dissertation') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('1410', 'LANG', 'Chinese I') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('4455', 'LANG', 'Chinese Calligraphy') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('4480', 'LANG', 'Chinese Lang, Culture & Film') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('6980', 'LGHT', 'Master''s Project') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('2110', 'LITR', 'Intro To Literature') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('4960', 'LITR', 'History Of Motion Pictures') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('1100', 'MGMT', 'Management In The Digital Age') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('2320', 'MGMT', 'Managerial Finance') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('4140', 'MGMT', 'Computer Info Systems') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('4800', 'MGMT', 'Business Ug Internship') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('4850', 'MGMT', 'Org Behavior In High Perf Org') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('2500', 'MTLE', 'Materials Laboratory Skills') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('4250', 'MTLE', 'Mechanical Properties Of Materials') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('6980', 'MTLE', 'Master''s Project') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('6990', 'MTLE', 'Master''s Thesis') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('9990', 'MTLE', 'Dissertation') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('2400', 'MATH', 'Intro Diff Equations') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('4090', 'MATH', 'Foundations Of Analysis') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('4100', 'MATH', 'Linear Algebra') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('4150', 'MATH', 'Graph Theory') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('4300', 'MATH', 'Intro To Complex Variables') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('4800', 'MATH', 'Numerical Computing') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('2220', 'MANE', 'Inventor''s Studio 1') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('2720', 'MANE', 'Fluid Mechanics') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('4030', 'MANE', 'Elements Of Mech Design') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('4060', 'MANE', 'Aerospace Struc & Materials') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('4070', 'MANE', 'Aerodynamics') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('4500', 'MANE', 'Modeling And Contrl Of Dyn Sys') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('4730', 'MANE', 'Heat Transfer') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('4880', 'MANE', 'Mane Laboratory Safety Program') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('6170', 'MANE', 'Mechanics Of Solids') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('6720', 'MANE', 'Adv Computnl Fluid Dynamics') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('6970', 'MANE', 'Master''s Professional Project') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('6980', 'MANE', 'Master''s Project') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('6990', 'MANE', 'Master''s Thesis') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('9990', 'MANE', 'Dissertation') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('2140', 'PHIL', 'Introduction To Formal Logic') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('4130', 'PHIL', 'Philosophy Of Science') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('4500', 'PHIL', 'Bioethics') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('1110', 'PHYS', 'Physics I (s)') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('1200', 'PHYS', 'Physics II') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('2350', 'PHYS', 'Experimental Physics') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('2961', 'PHYS', 'Intro Physics Teach Practicum') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('2962', 'PHYS', 'Computing For Physicists') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('2963', 'PHYS', 'Phys Teaching Practicum') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('4962', 'PHYS', 'Group Theory For Physicists') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('6980', 'PHYS', 'Master''s Project') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('2310', 'PSYC', 'Research Methods And Statistics I') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('2960', 'PSYC', 'Well-being:creating A Toolbox') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('4360', 'PSYC', 'Behavioral Neuroscience') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('4370', 'PSYC', 'Cognitive Psychology') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('4430', 'PSYC', 'Psychology Of Mindfulness') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('4700', 'PSYC', 'Hormones, Brain & Behavior') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('4730', 'PSYC', 'Positive Psychology') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('4961', 'PSYC', 'Models Of Mental Processes') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('4962', 'PSYC', 'Physics Meets Social Sciences') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('2300', 'STSO', 'Environment And Society') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('2520', 'STSO', 'Sociology') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('4100', 'STSO', 'Pd - Tech Issues & Solutions') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('4250', 'STSO', 'Bioethics') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('4260', 'STSO', 'Food, Farms, And Famine') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('4360', 'STSO', 'Commty Engmnt: Climate Chg') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('4600', 'STSO', 'Design & Innovation Studio A') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('1110', 'WRIT', 'Writing In Context') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('1769', 'WRIT', 'Intro To Creativewriting') ON CONFLICT (dept_prefix, code) DO NOTHING;
INSERT INTO courses(code, dept_prefix, course_name) VALUES('2340', 'WRIT', 'Speech Communication') ON CONFLICT (dept_prefix, code) DO NOTHING;
